########################################################################################
# CONFIGURATION GITLAB
########################################################################################

---
- name: Configuration GitLab
  hosts: gitlab

  tasks:
    - name: Créer le répertoire /etc/gitlab/ssl s'il n'existe pas
      file:
        path: /etc/gitlab/ssl
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Copier le certificat dans /etc/gitlab/ssl
      copy:
        src: /mnt/c/Users/anais/OneDrive/Bureau/Projets_pro/SSO_wicth_Docker/LAB-SSO_with_Docker/Terraform/certs/gitlab.lab.crt
        dest: /etc/gitlab/ssl/gitlab.lab.crt
        owner: root
        group: root
        mode: '0644'

    - name: Copier la clé privée dans /etc/gitlab/ssl
      copy:
        src: /mnt/c/Users/anais/OneDrive/Bureau/Projets_pro/SSO_wicth_Docker/LAB-SSO_with_Docker/Terraform/certs/gitlab.lab.key
        dest: /etc/gitlab/ssl/gitlab.lab.key
        owner: root
        group: root
        mode: '0600'

    - name: Met à jour l'external_url
      lineinfile:
        path: /etc/gitlab/gitlab.rb
        regexp: "^external_url"
        line: "external_url 'https://gitlab.lab'"
        create: yes
        backup: yes

    - name: Copier fichier gitlab.rb avec config OAuth
      copy:
        dest: /tmp/gitlab.rb
        content: |
          external_url 'https://gitlab.lab'
          gitlab_rails['omniauth_enabled'] = true
          gitlab_rails['omniauth_allow_single_sign_on'] = ['openid_connect']
          gitlab_rails['omniauth_block_auto_created_users'] = false
          gitlab_rails['omniauth_providers'] = [
            {
              name: 'openid_connect',
              label: 'Keycloak',
              args: {
                name: 'openid_connect',
                scope: ['openid', 'profile', 'email'],
                response_type: 'code',
                issuer: 'https://keycloak.lab/auth/realms/gitlab-realm',
                discovery: true,
                client_auth_method: 'basic',
                client_id: 'gitlab-client',
                client_secret: 'SECRETPASSECRET',
                redirect_uri: 'https://gitlab.lab/users/auth/openid_connect/callback'
              }
            }
          ]
      delegate_to: localhost

    - name: Copier gitlab.rb dans le conteneur GitLab
      command: docker cp /tmp/gitlab.rb gitlab:/etc/gitlab/gitlab.rb
      delegate_to : localhost

    - name: Reconfigurer GitLab
      command: docker exec gitlab gitlab-ctl reconfigure
      delegate_to : localhost

    - name: Restart GitLab
      command: gitlab-ctl restart